version: '3.8'

services:
  # PostgreSQL - Dados relacionais
  postgres:
    image: postgres:15-alpine
    container_name: dibea-postgres
    environment:
      POSTGRES_DB: dibea
      POSTGRES_USER: dibea
      POSTGRES_PASSWORD: dibea123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dibea-network

  # Redis - Cache e sessões
  redis:
    image: redis:7-alpine
    container_name: dibea-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - dibea-network

  # Neo4j - Grafo de conhecimento
  neo4j:
    image: neo4j:5.15-community
    container_name: dibea-neo4j
    environment:
      NEO4J_AUTH: neo4j/dibea123
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*,gds.*
      NEO4J_dbms_security_procedures_allowlist: apoc.*,gds.*
      NEO4J_apoc_export_file_enabled: true
      NEO4J_apoc_import_file_enabled: true
      NEO4J_apoc_import_file_use__neo4j__config: true
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - dibea-network

  # MinIO - Armazenamento de arquivos
  minio:
    image: minio/minio:latest
    container_name: dibea-minio
    environment:
      MINIO_ROOT_USER: dibea
      MINIO_ROOT_PASSWORD: dibea123456
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - dibea-network

  # Elasticsearch - Busca e indexação de documentos
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: dibea-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - dibea-network

volumes:
  postgres_data:
  redis_data:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
  minio_data:
  elasticsearch_data:

networks:
  dibea-network:
    driver: bridge
