apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-pvc
  namespace: dibea
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dibea-n8n
  namespace: dibea
  labels:
    app: dibea-n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dibea-n8n
  template:
    metadata:
      labels:
        app: dibea-n8n
    spec:
      containers:
      - name: n8n
        image: n8nio/n8n:latest
        ports:
        - containerPort: 5678
        env:
        - name: N8N_BASIC_AUTH_ACTIVE
          value: "true"
        - name: N8N_BASIC_AUTH_USER
          valueFrom:
            secretKeyRef:
              name: dibea-secrets
              key: N8N_BASIC_AUTH_USER
        - name: N8N_BASIC_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dibea-secrets
              key: N8N_BASIC_AUTH_PASSWORD
        - name: N8N_HOST
          value: "localhost"
        - name: N8N_PORT
          value: "5678"
        - name: N8N_PROTOCOL
          value: "http"
        - name: WEBHOOK_URL
          valueFrom:
            configMapKeyRef:
              name: dibea-config
              key: WEBHOOK_URL
        - name: GENERIC_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: dibea-config
              key: GENERIC_TIMEZONE
        volumeMounts:
        - name: n8n-storage
          mountPath: /home/node/.n8n
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5678
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5678
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: n8n-storage
        persistentVolumeClaim:
          claimName: n8n-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: dibea-n8n
  namespace: dibea
  labels:
    app: dibea-n8n
spec:
  type: LoadBalancer
  ports:
  - port: 5678
    targetPort: 5678
    protocol: TCP
  selector:
    app: dibea-n8n
